backend:
  name: github
  repo: dotik-agency/site
  branch: master
  
media_folder: content/assets
public_folder: ../assets

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: faq
    label: Faq
    folder: content/faq
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
  - name: projects
    label: Project
    folder: content/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author }
  

